### ISSUE TITLE
Dosage.site.coding should be 0..*

### ISSUE THREAD

**Issue by brettesler-ext** [hl7au/au-fhir-base-stu3#16]
https://jira.digitalhealth.gov.au/browse/CIFMM-2821  "HL7 AU STU3 Base Encounter + Dosage fixes"
and Vikas in his review queried whether the following code should have the "<max value="1"/> " deleted ie 

The following code can be found at:
http://build.fhir.org/ig/hl7au/au-fhir-base-stu3/StructureDefinition-au-dosage.xml.html
Dosage.site.coding should be 0..* rather than constrained to 0..1 as per the following code:
<element id="Dosage.site.coding">
      <path value="Dosage.site.coding"/>
      <max value="1"/>

Can I delete <max value="1"/> ?
Your thoughts?
Cheers
David McKillop

**Comment by brettesler-ext** [comment]
Meds WG agrees

**Comment by davidmckillop-ADHA** [comment]
Resolved with changes done in PR https://github.com/hl7au/au-fhir-base-stu3/pull/18
