### ISSUE TITLE
Medication-strength-text extension not in HL7 Au STU3 build anymore?

### ISSUE THREAD

**Issue by dbojicic-agency** [hl7au/au-fhir-base-stu3#2]
medication-strength-text extension is not in the HL7 Au Base STU3 build anymore. It is still listed in the extensions page: http://build.fhir.org/ig/hl7au/au-fhir-base-stu3/StructureDefinition-medication-strength-text.html.
Please confirm the extension is removed from the build.

**Comment by brettesler-ext** [comment]
yes - is removed by committee
