### ISSUE TITLE
404s on http://build.fhir.org/ig/hl7au/au-fhir-base-stu3/profiles.html

### ISSUE THREAD

**Issue by richardtownleyoneill-ADHA** [hl7au/au-fhir-base-stu3#4]
From http://build.fhir.org/ig/hl7au/au-fhir-base-stu3/profiles.html the following links return 404
AU Base Immunisation Recommendation
AU Base Specimen

**Comment by SatyaYelisetti** [comment]
Yes, these two profiles are missing there entries in ig.xml

**Comment by brettesler-ext** [comment]
fixed in commit 0c1b169
