### ISSUE TITLE
Medication.ingredient.item -AMT slice on Coding only allows for AMT MP codes

### ISSUE THREAD

**Issue by dbojicic-agency** [hl7au/au-fhir-base-stu3#6]
Medication.ingredient.item[x]:itemCodeableConcept.coding is sliced on value:system, with an 
amtMP slice defined with binding to AMT Medicinal Product with the strength of required. This does not allow for any other SNOMED codes, e.g. substance codes, which is an issue. Maybe remove the slice and bind Medication.ingredient.item[x]:itemCodeableConcept to the AMT with the strength of preferred? Is that an option given this profile has been through a ballot?

**Comment by brettesler-ext** [comment]
yes that is good - will notify when done

**Comment by RichardTON** [comment]
Medication.code.coding is optional, so I should be able to supply just Medication.code.text, but that triggers ALL of the inv-amt- invariants.
This suggests that all instances of Medication with a value for code will fail at least 6 constraints.

**Comment by brettesler-ext** [comment]
still outstanding; BE will review other slicing throughout IG where there is only one option: change slice (required) → binding as preferred

**Comment by richardtownleyoneill-ADHA** [comment]
Slicing removed in pull request #13

**Comment by brettesler-ext** [comment]
Need to fix coding slice discriminators to system only not 
Slice: Unordered, Open by value:system, value:code see #9

**Comment by brettesler-ext** [comment]
fixed
