### ISSUE TITLE
Medication.code.coding is sliced on value sets that are not enumerated

### ISSUE THREAD

**Issue by richardtownleyoneill-ADHA** [hl7au/au-fhir-base-stu3#9]
According to http://build.fhir.org/profiling.html#discriminator slicing using binding demands that the value sets have enumerated values. PBS, GTIN and AMT value sets are not and will not be enumerated value sets.
A different slicing is required.

**Comment by brettesler-ext** [comment]
Leave AMT binding as required - this would affect those with none AMT medicines using SNOMED.

**Comment by richardtownleyoneill-ADHA** [comment]
Slicing changed in pull request #13

**Comment by brettesler-ext** [comment]
fix this in the other resource types

**Comment by brettesler-ext** [comment]
fixed
